/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      // link: { type: 'doc', id: 'intro/introduction' },
      items: [
        {
          type: 'doc',
          label: 'Welcome to Ronin',
          id: 'intro/introduction',
        },
        {
          type: 'doc',
          label: 'Whitepaper (Testnet)',
          id: 'intro/whitepaper',
        },
        {
          type: 'doc',
          label: 'Roadmap',
          id: 'intro/road-map',
        },
        {
          type: 'category',
          label: 'Ronin Network',
          items: [
            {
              type: 'doc',
              label: 'Mainnet',
              id: 'intro/mainnet',
            },
            {
              type: 'doc',
              label: 'Saigon Testnet',
              id: 'intro/saigon-testnet',
            },
          ],       
        },  
        {
          type: 'doc',
          label: 'Tokenomic',
          id: 'intro/tokenomic',
        },
        {
          type: 'doc',
          label: 'Transaction life cycle',
          id: 'intro/transaction-lifecycle',
        },      
      ],
    },
    {
      type: 'category',
      label: 'Staking (Testnet)',
      link: { type: 'doc', id: 'stake/staking' },
      items: [
        {
          type: 'doc',
          label: 'Access the dashboard',
          id: 'stake/dashboard',
        },
        {
          type: 'doc',
          label: 'Delegate to a validator',
          id: 'stake/delegate',
        },
        {
          type: 'doc',
          label: 'Withdraw and move stake',
          id: 'stake/withdraw&move',
        },
        {
          type: 'doc',
          label: 'Claim reward',
          id: 'stake/claim',
        },
      ],
    },
    {
      type: 'category',
      label: 'Validator',
      link: { type: 'doc', id: 'components/validators' },
      items: [ 
        {
          type: 'category',
          label: 'Mainnet',          
          items: [
                {
                  type: 'link',
                  label: 'API',
                  href: 'https://documenter.getpostman.com/view/1372857/UVeKqQMn',
                },
                {
                  type: 'doc',
                  label: 'CLI',
                  id: 'validator/cli',
                },
                {
                  type: 'doc',
                  label: 'Minimum requirements',
                  id: 'validator/minimum-requirements',
                },
                {
                  type: 'doc',
                  label: 'Responsibilities',
                  id: 'validator/responsibilities',
                },
                {
                  type: 'doc',
                  label: 'Run a Validator node',
                  id: 'validator/running-validating-node',
                },
                {
                  type: 'doc',
                  label: 'Run a Non Validator node',
                  id: 'validator/running-non-validating-node',
                },
                {
                  type: 'doc',
                  label: 'Upgrade Ronin Node',
                  id: 'validator/upgrade-ronin-node',
                },
          ],
        }, 
        {
          type: 'category',
          label: 'Testnet',
          link: { type: 'doc', id: 'validator/val' },
          items: [
            {
              type: 'doc',
              label: 'Validator onboarding',
              id: 'validator/registration',
            },
            {
              type: 'doc',
              label: 'Setup a Validator node',
              id: 'validator/setup',
            },
          ],
        },
        // {
        //   type: 'doc',
        //   label: 'Validator responsibility',
        //   id: 'validator/responsibility',
        // },
        // {
        //   type: 'doc',
        //   label: 'Set up a validator node',
        //   id: 'validator/setup',
        // },
        // {
        //   type: 'doc',
        //   label: 'Registration',
        //   id: 'validator/registration',
        // },
      ],
    },
    {
      type: 'category',
      label: 'Bridge',
      // link: { type: 'doc', id: 'components/ronin-bridge-v2' },
      items: [
        {
          type: 'doc',
          label: 'Bridge V2',
          id: 'bridge/ronin-bridge-v2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      link: { type: 'doc', id: 'governance/gov' },
      items: [
        // {
        //   type: 'doc',
        //   label: 'Create a proposal',
        //   id: 'governance/create',
        // },
        // {
        //   type: 'doc',
        //   label: 'Vote on a proposal',
        //   id: 'governance/vote',
        // },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guides',
      // link: { type: 'doc', id: 'developer/dev' },
      items: [
        {
          type: 'category',
          label: 'Ronin Wallet Integration',
          items: [
            {
              type: 'doc',
              label: 'Wallet provider',
              id: 'developer-guide/integrate-ronin-wallet',
            },
            {
              type: 'doc',
              label: 'Network switching',
              id: 'developer-guide/switch-wallet-to-testnet',
            },
          ]
        },
        {
          type: 'category',
          label: 'Smart contract deploying',
          items: [
            {
              type: 'doc',
              label: 'Using Truffle',
              id: 'developer-guide/smart-contract-deploying/using-truffle',
            },
            {
              type: 'doc',
              label: 'Using Hardhat',
              id: 'developer-guide/smart-contract-deploying/using-hardhat',
            },
          ],
        },
      ],
    },
  ],
}

module.exports = sidebars
